name: my called workflow
on:
  workflow_call:
    inputs:
      first-name:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@master
       - name: say something
         run: |
             echo "Firstname is ${inputs.first-name}"
